services:
  database:
    image: postgres:latest
    container_name: database
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=database
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres

  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    image: backend:latest
    container_name: backend
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on:
      - database

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    image: frontend:latest
    container_name: frontend
    restart: unless-stopped
    ports:
      - 8080:8080
