services:
  database:
    image: postgres:latest
    container_name: database
    restart: unless-stopped
    environment:
      - POSTGRES_DB=database
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
    networks:
      - network

  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    image: backend:latest
    container_name: backend
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - network
    depends_on:
      - database

networks:
  network:
    driver: bridge
