services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=database
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    ports:
      - 80:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on:
      - postgres

  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    image: backend:latest
    container_name: backend
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./go/docs/swagger.json:/app/swagger.json
    depends_on:
      - postgres

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    image: frontend:latest
    container_name: frontend
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./static:/app

  swagger:
    image: swaggerapi/swagger-ui
    container_name: swagger
    restart: unless-stopped
    ports:
      - 8090:8090
    environment:
      - PORT=8090
      - SWAGGER_JSON_URL=http://localhost:3000/swagger
    depends_on:
      - backend
