services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=database
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
    volumes:
      - ./sql:/app

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    ports:
      - 80:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on:
      - postgres

  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    image: backend:latest
    container_name: backend
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./go/docs/swagger.json:/app/swagger.json
    depends_on:
      - postgres

  users:
    build:
      context: .
      dockerfile: services/users/Dockerfile
    image: users:latest
    container_name: users
    restart: unless-stopped
    ports:
      - 3001:3001
    depends_on:
      - postgres

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    image: frontend:latest
    container_name: frontend
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./static:/app

  swagger:
    image: swaggerapi/swagger-ui
    container_name: swagger
    restart: unless-stopped
    ports:
      - 8090:8090
    environment:
      - PORT=8090
      - SWAGGER_JSON_URL=http://localhost:3000/swagger
    depends_on:
      - backend

  kong:
    image: kong:latest
    container_name: kong
    restart: unless-stopped
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kongpass
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001,0.0.0.0:8444 ssl
      KONG_ADMIN_GUI_URL: http://localhost:8002
    ports:
      - 8000:8000
      - 8443:8443
      - 127.0.0.1:8001:8001
      - 127.0.0.1:8002:8002
      - 127.0.0.1:8444:8444

  kong-database:
    image: postgres:latest
    container_name: kong-database
    restart: unless-stopped
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=kong
      - POSTGRES_PASSWORD=kongpass
      - POSTGRES_USER=kong
