// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"voting-system/ent/complaint"
	"voting-system/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ComplaintDelete is the builder for deleting a Complaint entity.
type ComplaintDelete struct {
	config
	hooks    []Hook
	mutation *ComplaintMutation
}

// Where appends a list predicates to the ComplaintDelete builder.
func (cd *ComplaintDelete) Where(ps ...predicate.Complaint) *ComplaintDelete {
	cd.mutation.Where(ps...)
	return cd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (cd *ComplaintDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, cd.sqlExec, cd.mutation, cd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (cd *ComplaintDelete) ExecX(ctx context.Context) int {
	n, err := cd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (cd *ComplaintDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(complaint.Table, sqlgraph.NewFieldSpec(complaint.FieldID, field.TypeInt))
	if ps := cd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, cd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	cd.mutation.done = true
	return affected, err
}

// ComplaintDeleteOne is the builder for deleting a single Complaint entity.
type ComplaintDeleteOne struct {
	cd *ComplaintDelete
}

// Where appends a list predicates to the ComplaintDelete builder.
func (cdo *ComplaintDeleteOne) Where(ps ...predicate.Complaint) *ComplaintDeleteOne {
	cdo.cd.mutation.Where(ps...)
	return cdo
}

// Exec executes the deletion query.
func (cdo *ComplaintDeleteOne) Exec(ctx context.Context) error {
	n, err := cdo.cd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{complaint.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (cdo *ComplaintDeleteOne) ExecX(ctx context.Context) {
	if err := cdo.Exec(ctx); err != nil {
		panic(err)
	}
}
