// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"voting-system/ent/voter"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Voter is the model entity for the Voter schema.
type Voter struct {
	config
	// ID of the ent.
	ID           int `json:"id,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Voter) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case voter.FieldID:
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Voter fields.
func (v *Voter) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case voter.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			v.ID = int(value.Int64)
		default:
			v.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Voter.
// This includes values selected through modifiers, order, etc.
func (v *Voter) Value(name string) (ent.Value, error) {
	return v.selectValues.Get(name)
}

// Update returns a builder for updating this Voter.
// Note that you need to call Voter.Unwrap() before calling this method if this Voter
// was returned from a transaction, and the transaction was committed or rolled back.
func (v *Voter) Update() *VoterUpdateOne {
	return NewVoterClient(v.config).UpdateOne(v)
}

// Unwrap unwraps the Voter entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (v *Voter) Unwrap() *Voter {
	_tx, ok := v.config.driver.(*txDriver)
	if !ok {
		panic("ent: Voter is not a transactional entity")
	}
	v.config.driver = _tx.drv
	return v
}

// String implements the fmt.Stringer.
func (v *Voter) String() string {
	var builder strings.Builder
	builder.WriteString("Voter(")
	builder.WriteString(fmt.Sprintf("id=%v", v.ID))
	builder.WriteByte(')')
	return builder.String()
}

// Voters is a parsable slice of Voter.
type Voters []*Voter
