// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Candidate is the predicate function for candidate builders.
type Candidate func(*sql.Selector)

// Comment is the predicate function for comment builders.
type Comment func(*sql.Selector)

// Complaint is the predicate function for complaint builders.
type Complaint func(*sql.Selector)

// Election is the predicate function for election builders.
type Election func(*sql.Selector)

// FAQ is the predicate function for faq builders.
type FAQ func(*sql.Selector)

// Feedback is the predicate function for feedback builders.
type Feedback func(*sql.Selector)

// Organizer is the predicate function for organizer builders.
type Organizer func(*sql.Selector)

// Profile is the predicate function for profile builders.
type Profile func(*sql.Selector)

// Result is the predicate function for result builders.
type Result func(*sql.Selector)

// Setting is the predicate function for setting builders.
type Setting func(*sql.Selector)

// Tag is the predicate function for tag builders.
type Tag func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// Vote is the predicate function for vote builders.
type Vote func(*sql.Selector)

// Voter is the predicate function for voter builders.
type Voter func(*sql.Selector)
