definitions:
  generated.User:
    properties:
      created_at:
        description: CreatedAt holds the value of the "created_at" field.
        type: string
      email:
        description: Email holds the value of the "email" field.
        type: string
      id:
        description: ID of the ent.
        type: integer
      last_login:
        description: LastLogin holds the value of the "last_login" field.
        type: string
    type: object
  routes.Credentials:
    properties:
      email:
        description: |-
          Электронная почта пользователя
          required: true
        type: string
      password:
        description: |-
          Пароль пользователя
          required: true
        type: string
    type: object
  routes.SignupResponse:
    properties:
      id:
        description: ID вновь созданного пользователя
        type: integer
      message:
        description: Сообщение об успешном создании пользователя
        type: string
    type: object
  routes.TokenResponse:
    properties:
      token:
        description: JWT-токен
        type: string
    type: object
info:
  contact: {}
paths:
  /login:
    post:
      consumes:
      - application/json
      description: Аутентификация пользователя и возврат JWT-токена
      parameters:
      - description: Учетные данные пользователя
        in: body
        name: credentials
        required: true
        schema:
          $ref: '#/definitions/routes.Credentials'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/routes.TokenResponse'
        "400":
          description: Неверный формат запроса
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Неверный пароль
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Внутренняя ошибка сервера
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Вход пользователя
      tags:
      - Аутентификация
  /signup:
    post:
      consumes:
      - application/json
      description: Регистрация нового пользователя
      parameters:
      - description: Учетные данные пользователя
        in: body
        name: credentials
        required: true
        schema:
          $ref: '#/definitions/routes.Credentials'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/routes.SignupResponse'
        "400":
          description: Неверный формат запроса или ошибка при создании пользователя
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Регистрация пользователя
      tags:
      - Аутентификация
  /users:
    get:
      consumes:
      - application/json
      description: Получает список всех зарегистрированных пользователей
      produces:
      - application/json
      responses:
        "200":
          description: Список пользователей
          schema:
            items:
              $ref: '#/definitions/generated.User'
            type: array
        "500":
          description: Внутренняя ошибка сервера
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Получить всех пользователей
      tags:
      - Пользователи
  /users/{id}:
    get:
      consumes:
      - application/json
      description: Получает пользователя по уникальному идентификатору
      parameters:
      - description: ID пользователя
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Данные пользователя
          schema:
            $ref: '#/definitions/generated.User'
        "400":
          description: Неверный ID
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Пользователь не найден
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Получить пользователя
      tags:
      - Пользователи
swagger: "2.0"
