--
-- PostgreSQL database dump
--
-- Dumped from database version 17.0 (Debian 17.0-1.pgdg120+1)
-- Dumped by pg_dump version 17.0 (Debian 17.0-1.pgdg120+1)
SET
    statement_timeout = 0;

SET
    lock_timeout = 0;

SET
    idle_in_transaction_session_timeout = 0;

SET
    transaction_timeout = 0;

SET
    client_encoding = 'UTF8';

SET
    standard_conforming_strings = on;

SELECT
    pg_catalog.set_config ('search_path', '', false);

SET
    check_function_bodies = false;

SET
    xmloption = content;

SET
    client_min_messages = warning;

SET
    row_security = off;

SET
    default_tablespace = '';

SET
    default_table_access_method = "heap";

--
-- Name: candidates; Type: TABLE; Schema: public; Owner: postgres
--
CREATE TABLE
    "public"."candidates" (
        "id" bigint NOT NULL,
        "create_time" timestamp
        with
            time zone NOT NULL,
            "update_time" timestamp
        with
            time zone NOT NULL,
            "name" character varying NOT NULL,
            "description" character varying NOT NULL,
            "photo_url" character varying,
            "votes_count" bigint DEFAULT 0 NOT NULL,
            "election_candidates" bigint
    );

ALTER TABLE "public"."candidates" OWNER TO "postgres";

--
-- Name: candidates_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--
ALTER TABLE "public"."candidates"
ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."candidates_id_seq" START
    WITH
        1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

--
-- Name: comments; Type: TABLE; Schema: public; Owner: postgres
--
CREATE TABLE
    "public"."comments" (
        "id" bigint NOT NULL,
        "create_time" timestamp
        with
            time zone NOT NULL,
            "update_time" timestamp
        with
            time zone NOT NULL,
            "contents" character varying NOT NULL,
            "comment_children" bigint,
            "election_comments" bigint,
            "user_comments" bigint
    );

ALTER TABLE "public"."comments" OWNER TO "postgres";

--
-- Name: comments_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--
ALTER TABLE "public"."comments"
ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."comments_id_seq" START
    WITH
        1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

--
-- Name: election_filters; Type: TABLE; Schema: public; Owner: postgres
--
CREATE TABLE
    "public"."election_filters" (
        "id" bigint NOT NULL,
        "has_first_name" boolean DEFAULT false NOT NULL,
        "has_last_name" boolean DEFAULT false NOT NULL,
        "has_birthdate" boolean DEFAULT false NOT NULL,
        "has_phone_number" boolean DEFAULT false NOT NULL,
        "has_bio" boolean DEFAULT false NOT NULL,
        "has_address" boolean DEFAULT false NOT NULL,
        "has_photo_url" boolean DEFAULT false NOT NULL,
        "election_filters" bigint NOT NULL
    );

ALTER TABLE "public"."election_filters" OWNER TO "postgres";

--
-- Name: election_filters_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--
ALTER TABLE "public"."election_filters"
ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."election_filters_id_seq" START
    WITH
        1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

--
-- Name: election_settings; Type: TABLE; Schema: public; Owner: postgres
--
CREATE TABLE
    "public"."election_settings" (
        "id" bigint NOT NULL,
        "create_time" timestamp
        with
            time zone NOT NULL,
            "is_active" boolean DEFAULT true NOT NULL,
            "is_anonymous" boolean DEFAULT false NOT NULL,
            "allow_comments" boolean DEFAULT true NOT NULL,
            "max_votes" bigint DEFAULT 1 NOT NULL,
            "duration" timestamp
        with
            time zone NOT NULL,
            "election_settings" bigint NOT NULL
    );

ALTER TABLE "public"."election_settings" OWNER TO "postgres";

--
-- Name: election_settings_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--
ALTER TABLE "public"."election_settings"
ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."election_settings_id_seq" START
    WITH
        1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

--
-- Name: elections; Type: TABLE; Schema: public; Owner: postgres
--
CREATE TABLE
    "public"."elections" (
        "id" bigint NOT NULL,
        "title" character varying NOT NULL,
        "description" character varying NOT NULL,
        "completed" boolean DEFAULT false NOT NULL,
        "user_elections" bigint
    );

ALTER TABLE "public"."elections" OWNER TO "postgres";

--
-- Name: elections_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--
ALTER TABLE "public"."elections"
ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."elections_id_seq" START
    WITH
        1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

--
-- Name: profiles; Type: TABLE; Schema: public; Owner: postgres
--
CREATE TABLE
    "public"."profiles" (
        "id" bigint NOT NULL,
        "first_name" character varying,
        "last_name" character varying,
        "birthdate" timestamp
        with
            time zone,
            "phone_number" character varying,
            "bio" character varying,
            "address" character varying,
            "photo_url" character varying,
            "user_profile" bigint NOT NULL
    );

ALTER TABLE "public"."profiles" OWNER TO "postgres";

--
-- Name: profiles_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--
ALTER TABLE "public"."profiles"
ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."profiles_id_seq" START
    WITH
        1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

--
-- Name: tag_elections; Type: TABLE; Schema: public; Owner: postgres
--
CREATE TABLE
    "public"."tag_elections" (
        "tag_id" bigint NOT NULL,
        "election_id" bigint NOT NULL
    );

ALTER TABLE "public"."tag_elections" OWNER TO "postgres";

--
-- Name: tags; Type: TABLE; Schema: public; Owner: postgres
--
CREATE TABLE
    "public"."tags" (
        "id" bigint NOT NULL,
        "name" character varying NOT NULL
    );

ALTER TABLE "public"."tags" OWNER TO "postgres";

--
-- Name: tags_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--
ALTER TABLE "public"."tags"
ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."tags_id_seq" START
    WITH
        1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--
CREATE TABLE
    "public"."users" (
        "id" bigint NOT NULL,
        "create_time" timestamp
        with
            time zone NOT NULL,
            "update_time" timestamp
        with
            time zone NOT NULL,
            "email" character varying NOT NULL,
            "password" character varying NOT NULL,
            "last_login" timestamp
        with
            time zone NOT NULL,
            "is_active" boolean DEFAULT true NOT NULL,
            "is_organizer" boolean DEFAULT false NOT NULL
    );

ALTER TABLE "public"."users" OWNER TO "postgres";

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--
ALTER TABLE "public"."users"
ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."users_id_seq" START
    WITH
        1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

--
-- Name: votes; Type: TABLE; Schema: public; Owner: postgres
--
CREATE TABLE
    "public"."votes" (
        "id" bigint NOT NULL,
        "create_time" timestamp
        with
            time zone NOT NULL,
            "is_active" boolean DEFAULT true NOT NULL,
            "candidate_votes" bigint,
            "user_votes" bigint
    );

ALTER TABLE "public"."votes" OWNER TO "postgres";

--
-- Name: votes_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--
ALTER TABLE "public"."votes"
ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."votes_id_seq" START
    WITH
        1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

--
-- Data for Name: candidates; Type: TABLE DATA; Schema: public; Owner: postgres
--
--
-- Data for Name: comments; Type: TABLE DATA; Schema: public; Owner: postgres
--
--
-- Data for Name: election_filters; Type: TABLE DATA; Schema: public; Owner: postgres
--
--
-- Data for Name: election_settings; Type: TABLE DATA; Schema: public; Owner: postgres
--
--
-- Data for Name: elections; Type: TABLE DATA; Schema: public; Owner: postgres
--
--
-- Data for Name: profiles; Type: TABLE DATA; Schema: public; Owner: postgres
--
INSERT INTO
    "public"."profiles" (
        "id",
        "first_name",
        "last_name",
        "birthdate",
        "phone_number",
        "bio",
        "address",
        "photo_url",
        "user_profile"
    )
VALUES
    (1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1);

--
-- Data for Name: tag_elections; Type: TABLE DATA; Schema: public; Owner: postgres
--
--
-- Data for Name: tags; Type: TABLE DATA; Schema: public; Owner: postgres
--
--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--
INSERT INTO
    "public"."users" (
        "id",
        "create_time",
        "update_time",
        "email",
        "password",
        "last_login",
        "is_active",
        "is_organizer"
    )
VALUES
    (
        1,
        '2024-12-17 08:34:29.117505+00',
        '2024-12-17 08:34:30.5692+00',
        'string@string.string',
        '$2a$10$ycUbrmdfA006UQ8P.42py.3AqdPh9Abby3TKE/OvNUxkT9lnIppci',
        '2024-12-17 08:34:30.5692+00',
        true,
        true
    );

--
-- Data for Name: votes; Type: TABLE DATA; Schema: public; Owner: postgres
--
--
-- Name: candidates_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--
SELECT
    pg_catalog.setval ('"public"."candidates_id_seq"', 1, false);

--
-- Name: comments_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--
SELECT
    pg_catalog.setval ('"public"."comments_id_seq"', 1, false);

--
-- Name: election_filters_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--
SELECT
    pg_catalog.setval ('"public"."election_filters_id_seq"', 1, false);

--
-- Name: election_settings_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--
SELECT
    pg_catalog.setval ('"public"."election_settings_id_seq"', 1, false);

--
-- Name: elections_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--
SELECT
    pg_catalog.setval ('"public"."elections_id_seq"', 1, false);

--
-- Name: profiles_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--
SELECT
    pg_catalog.setval ('"public"."profiles_id_seq"', 1, true);

--
-- Name: tags_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--
SELECT
    pg_catalog.setval ('"public"."tags_id_seq"', 1, false);

--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--
SELECT
    pg_catalog.setval ('"public"."users_id_seq"', 1, true);

--
-- Name: votes_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--
SELECT
    pg_catalog.setval ('"public"."votes_id_seq"', 1, false);

--
-- Name: candidates candidates_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--
ALTER TABLE ONLY "public"."candidates" ADD CONSTRAINT "candidates_pkey" PRIMARY KEY ("id");

--
-- Name: comments comments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--
ALTER TABLE ONLY "public"."comments" ADD CONSTRAINT "comments_pkey" PRIMARY KEY ("id");

--
-- Name: election_filters election_filters_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--
ALTER TABLE ONLY "public"."election_filters" ADD CONSTRAINT "election_filters_pkey" PRIMARY KEY ("id");

--
-- Name: election_settings election_settings_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--
ALTER TABLE ONLY "public"."election_settings" ADD CONSTRAINT "election_settings_pkey" PRIMARY KEY ("id");

--
-- Name: elections elections_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--
ALTER TABLE ONLY "public"."elections" ADD CONSTRAINT "elections_pkey" PRIMARY KEY ("id");

--
-- Name: profiles profiles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--
ALTER TABLE ONLY "public"."profiles" ADD CONSTRAINT "profiles_pkey" PRIMARY KEY ("id");

--
-- Name: tag_elections tag_elections_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--
ALTER TABLE ONLY "public"."tag_elections" ADD CONSTRAINT "tag_elections_pkey" PRIMARY KEY ("tag_id", "election_id");

--
-- Name: tags tags_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--
ALTER TABLE ONLY "public"."tags" ADD CONSTRAINT "tags_pkey" PRIMARY KEY ("id");

--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--
ALTER TABLE ONLY "public"."users" ADD CONSTRAINT "users_pkey" PRIMARY KEY ("id");

--
-- Name: votes votes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--
ALTER TABLE ONLY "public"."votes" ADD CONSTRAINT "votes_pkey" PRIMARY KEY ("id");

--
-- Name: election_filters_election_filters_key; Type: INDEX; Schema: public; Owner: postgres
--
CREATE UNIQUE INDEX "election_filters_election_filters_key" ON "public"."election_filters" USING "btree" ("election_filters");

--
-- Name: election_settings_election_settings_key; Type: INDEX; Schema: public; Owner: postgres
--
CREATE UNIQUE INDEX "election_settings_election_settings_key" ON "public"."election_settings" USING "btree" ("election_settings");

--
-- Name: profiles_user_profile_key; Type: INDEX; Schema: public; Owner: postgres
--
CREATE UNIQUE INDEX "profiles_user_profile_key" ON "public"."profiles" USING "btree" ("user_profile");

--
-- Name: tags_name_key; Type: INDEX; Schema: public; Owner: postgres
--
CREATE UNIQUE INDEX "tags_name_key" ON "public"."tags" USING "btree" ("name");

--
-- Name: users_email_key; Type: INDEX; Schema: public; Owner: postgres
--
CREATE UNIQUE INDEX "users_email_key" ON "public"."users" USING "btree" ("email");

--
-- Name: candidates candidates_elections_candidates; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--
ALTER TABLE ONLY "public"."candidates" ADD CONSTRAINT "candidates_elections_candidates" FOREIGN KEY ("election_candidates") REFERENCES "public"."elections" ("id") ON DELETE CASCADE;

--
-- Name: comments comments_comments_children; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--
ALTER TABLE ONLY "public"."comments" ADD CONSTRAINT "comments_comments_children" FOREIGN KEY ("comment_children") REFERENCES "public"."comments" ("id") ON DELETE SET NULL;

--
-- Name: comments comments_elections_comments; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--
ALTER TABLE ONLY "public"."comments" ADD CONSTRAINT "comments_elections_comments" FOREIGN KEY ("election_comments") REFERENCES "public"."elections" ("id") ON DELETE CASCADE;

--
-- Name: comments comments_users_comments; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--
ALTER TABLE ONLY "public"."comments" ADD CONSTRAINT "comments_users_comments" FOREIGN KEY ("user_comments") REFERENCES "public"."users" ("id") ON DELETE CASCADE;

--
-- Name: election_filters election_filters_elections_filters; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--
ALTER TABLE ONLY "public"."election_filters" ADD CONSTRAINT "election_filters_elections_filters" FOREIGN KEY ("election_filters") REFERENCES "public"."elections" ("id") ON DELETE CASCADE;

--
-- Name: election_settings election_settings_elections_settings; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--
ALTER TABLE ONLY "public"."election_settings" ADD CONSTRAINT "election_settings_elections_settings" FOREIGN KEY ("election_settings") REFERENCES "public"."elections" ("id") ON DELETE CASCADE;

--
-- Name: elections elections_users_elections; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--
ALTER TABLE ONLY "public"."elections" ADD CONSTRAINT "elections_users_elections" FOREIGN KEY ("user_elections") REFERENCES "public"."users" ("id") ON DELETE SET NULL;

--
-- Name: profiles profiles_users_profile; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--
ALTER TABLE ONLY "public"."profiles" ADD CONSTRAINT "profiles_users_profile" FOREIGN KEY ("user_profile") REFERENCES "public"."users" ("id") ON DELETE CASCADE;

--
-- Name: tag_elections tag_elections_election_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--
ALTER TABLE ONLY "public"."tag_elections" ADD CONSTRAINT "tag_elections_election_id" FOREIGN KEY ("election_id") REFERENCES "public"."elections" ("id") ON DELETE CASCADE;

--
-- Name: tag_elections tag_elections_tag_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--
ALTER TABLE ONLY "public"."tag_elections" ADD CONSTRAINT "tag_elections_tag_id" FOREIGN KEY ("tag_id") REFERENCES "public"."tags" ("id") ON DELETE CASCADE;

--
-- Name: votes votes_candidates_votes; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--
ALTER TABLE ONLY "public"."votes" ADD CONSTRAINT "votes_candidates_votes" FOREIGN KEY ("candidate_votes") REFERENCES "public"."candidates" ("id") ON DELETE SET NULL;

--
-- Name: votes votes_users_votes; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--
ALTER TABLE ONLY "public"."votes" ADD CONSTRAINT "votes_users_votes" FOREIGN KEY ("user_votes") REFERENCES "public"."users" ("id") ON DELETE SET NULL;

--
-- PostgreSQL database dump complete
--