-- Add new schema named "public"
CREATE SCHEMA IF NOT EXISTS "public";

-- Set comment to schema: "public"
COMMENT ON SCHEMA "public" IS 'standard public schema';

-- Create "users" table
CREATE TABLE
    "public"."users" (
        "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "create_time" timestamptz NOT NULL,
        "update_time" timestamptz NOT NULL,
        "email" character varying NOT NULL,
        "password" character varying NOT NULL,
        "last_login" timestamptz NOT NULL,
        "is_active" boolean NOT NULL DEFAULT true,
        "is_organizer" boolean NOT NULL DEFAULT false,
        PRIMARY KEY ("id")
    );

-- Create index "users_email_key" to table: "users"
CREATE UNIQUE INDEX "users_email_key" ON "public"."users" ("email");

-- Create "elections" table
CREATE TABLE
    "public"."elections" (
        "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "title" character varying NOT NULL,
        "description" character varying NOT NULL,
        "completed" boolean NOT NULL DEFAULT false,
        "user_elections" bigint NULL,
        PRIMARY KEY ("id"),
        CONSTRAINT "elections_users_elections" FOREIGN KEY ("user_elections") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL
    );

-- Create "candidates" table
CREATE TABLE
    "public"."candidates" (
        "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "create_time" timestamptz NOT NULL,
        "update_time" timestamptz NOT NULL,
        "name" character varying NOT NULL,
        "description" character varying NOT NULL,
        "photo_url" character varying NULL,
        "votes_count" bigint NOT NULL DEFAULT 0,
        "election_candidates" bigint NULL,
        PRIMARY KEY ("id"),
        CONSTRAINT "candidates_elections_candidates" FOREIGN KEY ("election_candidates") REFERENCES "public"."elections" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
    );

-- Create "comments" table
CREATE TABLE
    "public"."comments" (
        "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "create_time" timestamptz NOT NULL,
        "update_time" timestamptz NOT NULL,
        "contents" character varying NOT NULL,
        "comment_children" bigint NULL,
        "election_comments" bigint NULL,
        "user_comments" bigint NULL,
        PRIMARY KEY ("id"),
        CONSTRAINT "comments_comments_children" FOREIGN KEY ("comment_children") REFERENCES "public"."comments" ("id") ON UPDATE NO ACTION ON DELETE SET NULL,
        CONSTRAINT "comments_elections_comments" FOREIGN KEY ("election_comments") REFERENCES "public"."elections" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
        CONSTRAINT "comments_users_comments" FOREIGN KEY ("user_comments") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
    );

-- Create "election_filters" table
CREATE TABLE
    "public"."election_filters" (
        "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "has_first_name" boolean NOT NULL DEFAULT false,
        "has_last_name" boolean NOT NULL DEFAULT false,
        "has_birthdate" boolean NOT NULL DEFAULT false,
        "has_phone_number" boolean NOT NULL DEFAULT false,
        "has_bio" boolean NOT NULL DEFAULT false,
        "has_address" boolean NOT NULL DEFAULT false,
        "has_photo_url" boolean NOT NULL DEFAULT false,
        "election_filters" bigint NOT NULL,
        PRIMARY KEY ("id"),
        CONSTRAINT "election_filters_elections_filters" FOREIGN KEY ("election_filters") REFERENCES "public"."elections" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
    );

-- Create index "election_filters_election_filters_key" to table: "election_filters"
CREATE UNIQUE INDEX "election_filters_election_filters_key" ON "public"."election_filters" ("election_filters");

-- Create "election_settings" table
CREATE TABLE
    "public"."election_settings" (
        "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "create_time" timestamptz NOT NULL,
        "is_active" boolean NOT NULL DEFAULT true,
        "is_anonymous" boolean NOT NULL DEFAULT false,
        "allow_comments" boolean NOT NULL DEFAULT true,
        "max_votes" bigint NOT NULL DEFAULT 1,
        "duration" timestamptz NOT NULL,
        "election_settings" bigint NOT NULL,
        PRIMARY KEY ("id"),
        CONSTRAINT "election_settings_elections_settings" FOREIGN KEY ("election_settings") REFERENCES "public"."elections" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
    );

-- Create index "election_settings_election_settings_key" to table: "election_settings"
CREATE UNIQUE INDEX "election_settings_election_settings_key" ON "public"."election_settings" ("election_settings");

-- Create "profiles" table
CREATE TABLE
    "public"."profiles" (
        "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "first_name" character varying NULL,
        "last_name" character varying NULL,
        "birthdate" timestamptz NULL,
        "phone_number" character varying NULL,
        "bio" character varying NULL,
        "address" character varying NULL,
        "photo_url" character varying NULL,
        "user_profile" bigint NOT NULL,
        PRIMARY KEY ("id"),
        CONSTRAINT "profiles_users_profile" FOREIGN KEY ("user_profile") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
    );

-- Create index "profiles_user_profile_key" to table: "profiles"
CREATE UNIQUE INDEX "profiles_user_profile_key" ON "public"."profiles" ("user_profile");

-- Create "tags" table
CREATE TABLE
    "public"."tags" (
        "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "name" character varying NOT NULL,
        PRIMARY KEY ("id")
    );

-- Create index "tags_name_key" to table: "tags"
CREATE UNIQUE INDEX "tags_name_key" ON "public"."tags" ("name");

-- Create "tag_elections" table
CREATE TABLE
    "public"."tag_elections" (
        "tag_id" bigint NOT NULL,
        "election_id" bigint NOT NULL,
        PRIMARY KEY ("tag_id", "election_id"),
        CONSTRAINT "tag_elections_election_id" FOREIGN KEY ("election_id") REFERENCES "public"."elections" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
        CONSTRAINT "tag_elections_tag_id" FOREIGN KEY ("tag_id") REFERENCES "public"."tags" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
    );

-- Create "votes" table
CREATE TABLE
    "public"."votes" (
        "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "create_time" timestamptz NOT NULL,
        "is_active" boolean NOT NULL DEFAULT true,
        "candidate_votes" bigint NULL,
        "user_votes" bigint NULL,
        PRIMARY KEY ("id"),
        CONSTRAINT "votes_candidates_votes" FOREIGN KEY ("candidate_votes") REFERENCES "public"."candidates" ("id") ON UPDATE NO ACTION ON DELETE SET NULL,
        CONSTRAINT "votes_users_votes" FOREIGN KEY ("user_votes") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL
    );